---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    container_name: node-producer
    build: ./node-producer
    environment:
      BOOTSTRAP_SERVERS: kafka:9092

  webserver:
    container_name: webserver
    build: ./webserver
    ports:
      - 3000:3000
    environment:
      BOOTSTRAP_SERVERS: kafka:9092

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    depends_on:
      - webserver
    ports:
      - 80:8080
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
