---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    container_name: kafka
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: LISTENER_INT://0.0.0.0:9092,LISTENER_EXT://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INT://kafka:9092,LISTENER_EXT://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INT

  producer1:
    container_name: producer1
    build: ./java-producer
    volumes:
      - ./java-producer/drivers:/app/project/drivers
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      DRIVER_ID: driver-1
    command: "bash -c 'until kafkacat -b kafka:9092 -L | grep driver-augmented; \
                      do sleep 1; \
                      echo waiting for topic; \
                      done; \
                      java -classpath \"lib/*\" clients.Producer'"

  producer2:
    container_name: producer2
    build: ./java-producer
    volumes:
      - ./java-producer/drivers:/app/project/drivers
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      DRIVER_ID: driver-2
    command: "bash -c 'until kafkacat -b kafka:9092 -L | grep driver-augmented; \
                      do sleep 1; \
                      echo waiting for topic; \
                      done; \
                      java -classpath \"lib/*\" clients.Producer'"

  producer3:
    container_name: producer3
    build: ./java-producer
    volumes:
      - ./java-producer/drivers:/app/project/drivers
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      DRIVER_ID: driver-3
    command: "bash -c 'until kafkacat -b kafka:9092 -L | grep driver-augmented; \
                      do sleep 1; \
                      echo waiting for topic; \
                      done; \
                      java -classpath \"lib/*\" clients.Producer'"
                        
  producer4:
    container_name: producer4
    build: ./java-producer
    volumes:
      - ./java-producer/drivers:/app/project/drivers
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      DRIVER_ID: driver-4
    command: "bash -c 'until kafkacat -b kafka:9092 -L | grep driver-augmented; \
                      do sleep 1; \
                      echo waiting for topic; \
                      done; \
                      java -classpath \"lib/*\" clients.Producer'"

  producer5:
    container_name: producer5
    build: ./java-producer
    volumes:
      - ./java-producer/drivers:/app/project/drivers
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      DRIVER_ID: driver-5
    command: "bash -c 'until kafkacat -b kafka:9092 -L | grep driver-augmented; \
                      do sleep 1; \
                      echo waiting for topic; \
                      done; \
                      java -classpath \"lib/*\" clients.Producer'"

  # streams:
  #   container_name: streams
  #   build: ./streams
  #   environment:
  #     BOOTSTRAP_SERVERS: kafka:9092

  webserver:
    container_name: webserver
    build: ./webserver
    volumes:
      - ./webserver:/home/node/app
      - /home/node/app/node_modules/
    ports:
      - 3000:3000
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
    command: "bash -c 'until kafkacat -b kafka:9092 -L | grep driver-augmented; \
                      do sleep 1; \
                      echo waiting for topic; \
                      done; \
                      npm run start'"

  schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    hostname: schema-registry
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:9092'

  ksql-server:
    image: confluentinc/cp-ksql-server:5.3.1
    hostname: ksql-server
    container_name: ksql-server
    ports:
      - "8088:8088"
    environment:
      KSQL_CONFIG_DIR: "/etc/ksql"
      KSQL_LOG4J_OPTS: "-Dlog4j.configuration=file:/etc/ksql/log4j-rolling.properties"
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
      KSQL_HOST_NAME: ksql-server
      KSQL_APPLICATION_ID: "dev-class"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
      KSQL_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    depends_on:
      - webserver
    ports:
      - 80:8080
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  populate:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    container_name: populate
    volumes:
      - ./drivers.csv:/drivers.csv
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                       cub kafka-ready -b kafka:9092 1 300 && \
                       echo Creating topics... && \
                       kafka-topics --bootstrap-server kafka:9092 --create --topic driver --partitions 3 --replication-factor 1 && \
                       kafka-topics --bootstrap-server kafka:9092 --create --topic driver-positions --partitions 3 --replication-factor 1 && \
                       kafka-topics --bootstrap-server kafka:9092 --create --topic driver-positions-distance --partitions 3 --replication-factor 1 && \
                       kafka-topics --bootstrap-server kafka:9092 --create --topic driver-augmented --partitions 3 --replication-factor 1 && \
                       cat /drivers.csv | kafka-console-producer --broker-list kafka:9092 --topic driver --property key.separator=: --property parse.key=true'"

